version: '2.3'

networks:
  bridge:
    driver: bridge

services:

  metapage-app:
    build:
      context: .
    command: ["just", "get-in-docker"]
    environment:
      - "HIST_FILE=/root/.bash_history"
    volumes:
      - ./:/workspace
      # A trick to get local aliases, bash history, and symlinks working
      - ${HOME}:${HOME}
      - ${HOME}/.bash_history:/root/.bash_history
      - ${HOME}/.aliases:/root/.aliases
    networks:
      - bridge
    ports:
      - "4010:${PORT_METAPAGE_APP:-4010}"

  # By prepending any external urls with http://localhost:3000
  # e.g. http://localhost:3000/https://app.metapages.org/
  # we can transparently proxy metapages so they are all http
  # and cors won't break everything
  # If you change PORT_PROXY you'll need set the same port change in app-metapage-local
  proxy:
    image: imjacobclark/cors-container
    environment:
     - "PORT=${PORT_PROXY:-3000}"
    ports:
      - "${PORT_PROXY:-3000}:${PORT_PROXY:-3000}"
    networks:
      - bridge
